<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class LogsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        if (Schema::hasTable('academics')) {
            DB::table('academics')->insert([
            [
                'student_id' => '2025020024C1',
                'semester_id' => 1,
                'academic_date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(4)->toTimeString(),
                'time_out_remark' => 'Early',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                // 'time_out_monitor_name' column not present in DB
                'time_out_absent_validation' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remark' => 'Late',
                'educator_consideration' => null,
                'time_in_reason' => null,
                // 'time_in_monitor_name' column not present in DB
                'time_in_absent_validation' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],[
                'student_id' => '2025020028C1',
                'semester_id' => 1,
                'academic_date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(4)->toTimeString(),
                'time_out_remark' => 'On Time',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                // 'time_out_monitor_name' column not present in DB
                'time_out_absent_validation' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->subHours(2)->toTimeString(),
                'time_in_remark' => 'Early',
                'educator_consideration' => null,
                'time_in_reason' => null,
                // 'time_in_monitor_name' column not present in DB
                'time_in_absent_validation' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],[
                'student_id' => '2025010031C1',
                'semester_id' => 1,
                'academic_date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(5)->toTimeString(),
                'time_out_remark' => 'Late',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                // 'time_out_monitor_name' column not present in DB
                'time_out_absent_validation' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remark' => 'Early',
                'educator_consideration' => null,
                'time_in_reason' => null,
                // 'time_in_monitor_name' column not present in DB
                'time_in_absent_validation' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],
            ]);
        }

        if (Schema::hasTable('going_outs')) {
            DB::table('going_outs')->insert([
            [
                'student_id' => '2025010035C1',
                'going_out_date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(4)->toTimeString(),
                'time_out_remark' => 'Early',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remark' => 'Late',
                'educator_consideration' => null,
                'time_in_reason' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],[
                'student_id' => '2025010039C1',
                'going_out_date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(10)->toTimeString(),
                'time_out_remark' => 'On Time',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->subHours(2)->toTimeString(),
                'time_in_remark' => 'Early',
                'educator_consideration' => null,
                'time_in_reason' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],[
                'student_id' => '2025020036C1',
                'going_out_date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(5)->toTimeString(),
                'time_out_remark' => 'Late',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remark' => 'Early',
                'educator_consideration' => null,
                'time_in_reason' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],
            ]);
        }

        if (Schema::hasTable('intern_log')) {
            DB::table('intern_log')->insert([
            [
                'student_id' => '2025010035C1',
                'date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(4)->toTimeString(),
                'time_out_remark' => 'Early',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remark' => 'Late',
                'educator_consideration' => null,
                'time_in_reason' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],[
                'student_id' => '2025010039C1',
                'date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(10)->toTimeString(),
                'time_out_remark' => 'On Time',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->subHours(2)->toTimeString(),
                'time_in_remark' => 'Early',
                'educator_consideration' => null,
                'time_in_reason' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],[
                'student_id' => '2025020036C1',
                'date' => $now->copy()->toDateString(),
                'time_out' => $now->copy()->subHours(5)->toTimeString(),
                'time_out_remark' => 'Late',
                'time_out_consideration' => null,
                'time_out_reason' => null,
                'monitor_logged_out' => 0,
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remark' => 'Early',
                'educator_consideration' => null,
                'time_in_reason' => null,
                'monitor_logged_in' => 0,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],
            ]);
        }

        if (Schema::hasTable('going_home')) {
            DB::table('going_home')->insert([
                [
                'student_id' => '2025020020C1',
                'schedule_name' => 'Going Home',
                'date_time_out' => $now->copy()->subDays(5)->toDateString(),
                'time_out' => $now->copy()->subHours(5)->toTimeString(),
                'time_out_remarks' => 'On Time',
                'time_out_reason' => null,
                'time_out_consideration' => null,
                'date_time_in' => $now->copy()->toDateString(),
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remarks' => 'Late',
                'time_in_reason' => null,
                'time_in_consideration' => null,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],
            [
                'student_id' => '2025020022C1',
                'schedule_name' => 'Going Home',
                'date_time_out' => $now->copy()->subDays(5)->toDateString(),
                'time_out' => $now->copy()->subHours(5)->toTimeString(),
                'time_out_remarks' => 'On Time',
                'time_out_reason' => null,
                'time_out_consideration' => null,
                'date_time_in' => $now->copy()->toDateString(),
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remarks' => 'Late',
                'time_in_reason' => null,
                'time_in_consideration' => null,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
            ],
            [
                'student_id' => '2025010019C1',
                'schedule_name' => 'Going Home',
                'date_time_out' => $now->copy()->subDays(5)->toDateString(),
                'time_out' => $now->copy()->subHours(5)->toTimeString(),
                'time_out_remarks' => 'On Time',
                'time_out_reason' => null,
                'time_out_consideration' => null,
                'date_time_in' => $now->copy()->toDateString(),
                'time_in' => $now->copy()->toTimeString(),
                'time_in_remarks' => 'Late',
                'time_in_reason' => null,
                'time_in_consideration' => null,
                'is_manual_entry' => 0,
                'manual_entry_type' => null,
                'manual_entry_reason' => null,
                'manual_entry_monitor' => null,
                'manual_entry_timestamp' => null,
                'approval_status' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'created_by' => 'admin',
                'created_at' => $now,
                'updated_by' => 'admin',
                'updated_at' => $now,
                'is_deleted' => 0,
                ],
            ]);
        }
    }
}
